### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by mrsteyk** [kaeza/minetest-xban2#4]
Hello! I have a crash in you mod when playing my pack (DreamBuilder + Carbone-ng). Here is crash lines: http://pastebin.com/ngP1MS5L

**Comment by kaeza** [comment]
Both Dreambuilder and Carbone-NG are subgames. How can you be playing two subgames at the same time?

In any case, it seems Carbone-NG is using an older, incompatible version of `xban`. You'll have to remove either `xban` or `xban2` and it should fix the problem.

**Comment by mrsteyk** [comment]
I really long ago guessed that but anyway thanks!
